# Generated by Django 2.2 on 2020-06-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название пляжа')),
                ('full_name', models.TextField(verbose_name='Полное название')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.CharField(max_length=250, verbose_name='Электронная почта')),
                ('region', models.CharField(max_length=150, verbose_name='Регион')),
                ('accredited_organization', models.CharField(max_length=250, verbose_name='Организация проводившая аккредитацию')),
                ('certificate_number', models.CharField(max_length=150, verbose_name='Номер сертификата')),
                ('registrated_num', models.CharField(max_length=150, verbose_name='Регистрационный номер')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('ogrn', models.IntegerField(verbose_name='ОГРН')),
                ('category', models.CharField(max_length=250, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=250)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
